name: CICD Pipeline for Beer Catalog
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/fastapi:${{ github.ref_name }}

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name fastapi ghcr.io/${{ github.actor }}/beer:${{ github.ref_name }}

      - name: Wait for API to be ready
        run: sleep 10
        
      - name: Show container
        run: docker ps

      - name: Test endpoint
        run: curl -s http://localhost:8000/

      - name: Stop and clean up
        if: always()
        run: |
          docker stop fastapi
          docker rm fastapi